[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start:all"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
internalPort = 3000
